Repository NaYeongSeokGame/ImNayeoungSeokToo-client, pull requests merged in 2023-07, with the labels that each got.

#34 [INT-38] 폰트 파일 및 폰트/컬러 변수값 추가
  src/assets/fonts/GmarketSansTTFBold.woff
  src/assets/fonts/GmarketSansTTFLight.woff
  src/assets/fonts/GmarketSansTTFMedium.woff
  src/assets/fonts/NeoDunggeunmoPro-Regular.woff
  src/assets/fonts/font.css
  src/styles/colors.ts
  src/styles/fonts.ts
  src/styles/globalStyle.ts
Labels: 🧑‍🎨 Style

#35 [INT-9] 사운드 음량 조절
  src/constants/audioSetting.ts
  src/hooks/useAudio.ts
  src/hooks/useVolumeControl.ts
  src/stores/audio/actions.ts
  src/stores/audio/atoms.ts
  src/stores/audio/index.ts
  src/types/atom/audio/index.ts
Labels: ✨ Feature

#37 [INT-39] 메인페이지(Home) 구조 변경
  src/apis/quiz.ts
  src/components/main/CategoryCarousel/CategoryCarousel.style.ts
  src/components/main/CategoryCarousel/CategoryCarousel.tsx
  src/components/main/CategoryCarousel/CategoryCarouselImage.tsx
  src/components/pages/Home/Home.style.ts
  src/components/pages/Home/Home.tsx
  src/hooks/useGetPresetList.ts
  src/types/quiz.ts
Labels: ✨ Feature, 🧑‍🎨 Style

#36 [INT-15] 문제 풀이 시간 설정
  src/components/main/GameStartModal/GameStartModal.tsx
  src/hooks/usePresetSetting.ts
Labels: 🐞 Bug

#38 [INT-14] yarn 에서 pnpm 으로 패키지 매니저 수정
  .github/auto-assign-setting.yml
  .github/pull_request_template.md
  .github/workflows/development.yml
  .github/workflows/production.yml
  deploy.sh
  pnpm-lock.yaml
  yarn.lock
Labels: ⚙ Setting

#39 [INT-49] 문제 풀이 시간 변경 기능
  src/components/pages/QuizPlay/QuizPlay.tsx
  src/hooks/usePresetSetting.ts
Labels: ✨ Feature

#40 [INT-54] Navigator 및 Layout 수정, Router 로직 분리
  src/assets/icons/checkIcon.svg
  src/assets/icons/homeIcon.svg
  src/assets/icons/searchIcon.svg
  src/assets/icons/settingIcon.svg
  src/components/common/BasicLayout/BasicLayout.style.ts
  src/components/common/BasicLayout/BasicLayout.tsx
  src/components/common/GameManage/GameManage.style.tsx
  src/components/common/GameManage/GameManage.tsx
  src/components/common/Navigator/Navigator.style.ts
  src/components/common/Navigator/Navigator.tsx
  src/components/pages/TestAPI.tsx
  src/main.tsx
  src/routes/router.tsx
  tsconfig.json
Labels: 🔨 Refactor

#41 [INT-43] 링크 공유 페이지 추가
  .template.env
  global.d.ts
  src/assets/icons/facebookIcon.svg
  src/assets/icons/kakaoTalkIcon.svg
  src/assets/icons/twitterIcon.svg
  src/assets/icons/urlLinkIcon.svg
  src/components/pages/QuizResult/QuizResult.style.ts
  src/components/pages/QuizResult/QuizResult.tsx
  src/constants/resultComment.ts
  src/hooks/useShare.ts
  src/styles/fonts.ts
Labels: ✨ Feature

#42 [INT-44] 전체 프리셋 목록 페이지 추가
  src/assets/fonts/font.css
  src/assets/icons/PresetSearchIcon.svg
  src/assets/images/PresetBackground.svg
  src/assets/images/PresetCard.svg
  src/assets/images/PresetHashtag.svg
  src/assets/images/PresetImage.svg
  src/assets/images/PresetTitle.svg
  src/components/common/Navigator/Navigator.tsx
  src/components/main/PresetCard/PresetCard.style.ts
  src/components/main/PresetCard/PresetCard.tsx
  src/components/main/PresetCard/index.tsx
  src/components/pages/Home/Home.tsx
  src/components/pages/QuizSearch/QuizSearch.style.tsx
  src/components/pages/QuizSearch/QuizSearch.tsx
  src/components/pages/QuizSearch/index.tsx
  src/main.tsx
  src/routes/router.tsx
  src/styles/fonts.ts
  src/styles/globalStyle.ts
Labels: ✨ Feature

#43 [INT-50] 메인 페이지 퍼블리싱
  src/components/main/CategoryCarousel/CategoryCarousel.style.ts
  src/components/main/CategoryCarousel/CategoryCarousel.tsx
  src/components/main/GameStartModal/GameStartModal.tsx
  src/components/main/PresetCard/PresetCard.style.tsx
  src/components/pages/Home/Home.style.ts
  src/components/pages/Home/Home.tsx
Labels: ✨ Feature

#46 [INT-45] 퀴즈 생성페이지(CreateQuiz) 구조 변경
  src/assets/fonts/font.css
  src/assets/icons/arrowIcon.svg
  src/assets/images/uploadQuizText.svg
  src/components/main/AddQuizModal/AddQuizModal.style.ts
  src/components/main/AddQuizModal/AddQuizModal.tsx
  src/components/main/CreateQuizImageView/CreateQuizImage.style.ts
  src/components/main/CreateQuizImageView/CreateQuizImage.tsx
  src/components/main/CreateQuizImageView/index.ts
  src/components/main/HastagInput/HashtagInput.tsx
  src/components/main/HastagInput/HastagInput.style.ts
  src/components/main/HastagInput/index.ts
  src/components/main/ToggleButton/ToggleButton.style.ts
  src/components/main/ToggleButton/ToggleButton.tsx
  src/components/main/ToggleButton/index.tsx
  src/components/pages/CreateQuiz/CreateQuiz.style.ts
  src/components/pages/CreateQuiz/CreateQuiz.tsx
  src/components/pages/QuizUpload/QuizUpload.style.ts
  src/components/pages/QuizUpload/QuizUpload.tsx
  src/styles/colors.ts
  src/styles/fonts.ts
  src/types/quiz.ts
Labels: ✨ Feature

#44 [INT-51] 퀴즈 풀이 페이지 퍼블리싱
  src/assets/images/timerImage.png
  src/components/main/PresetCard/PresetCard.style.ts
  src/components/main/PresetCard/PresetCard.style.tsx
  src/components/main/PresetCard/PresetCard.tsx
  src/components/pages/QuizPlay/QuizPlay.style.ts
  src/components/pages/QuizPlay/QuizPlay.tsx
  src/hooks/useTimer.ts
  src/styles/colors.ts
Labels: ✨ Feature
