Repository NaYeongSeokGame/ImNayeoungSeokToo-client, pull requests merged in 2023-09, with the labels that each got.

#51 [INT-58] 프리셋 검색 페이지 기능 구현
  src/apis/quiz.ts
  src/components/main/PresetCard/PresetCard.style.ts
  src/components/pages/CreateQuiz/CreateQuiz.style.ts
  src/components/pages/Home/Home.tsx
  src/components/pages/QuizSearch/QuizSearch.style.tsx
  src/components/pages/QuizSearch/QuizSearch.tsx
  src/constants/queryKey.ts
  src/hooks/useSearchPresetList.ts
  src/styles/fonts.ts
  src/types/quiz.ts
Labels: ✨ Feature

#52 [INT-70] 퀴즈 검색 페이지 레이아웃 수정
  src/components/pages/QuizSearch/QuizSearch.style.tsx
Labels: 🧑‍🎨 Style

#53 [INT-71] fix : 사운드 볼륨이 저장한 대로 나오지 않는 오류 수정
  src/assets/images/landingText.svg
  src/assets/lotties/dot.json
  src/components/main/GameSettingModal/GameSettingModal.tsx
  src/components/pages/Landing/Landing.style.ts
  src/components/pages/Landing/Landing.tsx
  src/hooks/useVolumeControl.ts
  src/utils/playAudio.ts
Labels: 🐞 Bug
